package main

import "math"

const (
	TILE_SIZE    = 64
	MAP_NUM_ROWS = 13
	MAP_NUM_COLS = 20

	MINIMAP_SCALE_FACTOR float32 = 1

	WINDOW_WIDTH  = MAP_NUM_COLS * TILE_SIZE
	WINDOW_HEIGHT = MAP_NUM_ROWS * TILE_SIZE

	FOV_ANGLE = 60 * (math.Pi / 180)

	NUM_RAYS = WINDOW_WIDTH
)
